### ISSUE TITLE
Acc of last several checkpoints changed greatly 

### ISSUE THREAD

**Issue by mikon1995** [kujason/avod#123]
thanks for sharing your work firstly.
i'm confused with several points :
1. the Accuracy of last several checkpoints changed greatly, it seems strange i wonder if my results is wrong.
![baseline_host_car](https://user-images.githubusercontent.com/28284518/52840746-24169c00-3135-11e9-9b98-fc0aac4cc22d.jpg)

2. the code divided the dataset to two parts: car and people. then train the model independently with car/people configs.  my understanding is the final acc (~0.1.txt) in /scrips/offline_eval/results/ used two config models and two divided datasets.
how about the results in KITTI benchmark ... can we predict the three classes with an unified model? 

3. the cyclist acc and pedestrian acc seems opposite to authors.
thanks a lot!!

**Comment by kujason** [comment]
1. Try the settings recommended here for more stable training: https://github.com/kujason/avod/issues/29#issuecomment-379289149.
2. The cars and pedestrian+cyclists are trained separately due to severe class imbalance in the KITTI dataset, we did not try training them all together but it should be possible to set up.
3. We found that the results for pedestrians and cyclists varies a lot due to the low number of available labels
