### ISSUE TITLE
confused about the aug method

### ISSUE THREAD

**Issue by liyang0522** [kujason/avod#176]
if the method is lidar + image, what aug method should we do ?   It seems that only the flip aug can do both in lidar and image.
what about scale and translation? any one can explain it ! Thank you!!!

**Comment by patelrahil224** [comment]
Hi Li,

For given architecture scaling augmentation makes less sense because we are using feature pyramid network after feature extraction which already does prediction in different scale levels.

![image](https://user-images.githubusercontent.com/59541753/87283627-c63adf00-c4f5-11ea-9031-2883953cea47.png)
[https://arxiv.org/pdf/1612.03144.pdf]

Translation augmentation can be performed but the inputs of BEV from LIDAR and Front-view from camera has to be calibrated sepratly first before feeding to the same pipeline this could be the reason.

Please review the answer with other sources as well. That's just my understanding it could be wrong with extreme extent 

Regards,
Rahil

**Comment by patelrahil224** [comment]
Hi Li,

For given architecture scaling augmentation makes less sense because we are using feature pyramid network after feature extraction which already does prediction in different scale levels.

![image](https://user-images.githubusercontent.com/59541753/87284435-a8ba4500-c4f6-11ea-99a6-94dfcbc68d5c.png)
[https://arxiv.org/pdf/1612.03144.pdf](url)

Translation augmentation can be performed but the inputs of BEV from LIDAR and Front-view from camera has to be calibrated sepratly first before feeding to the same pipeline this could be the reason.

Please review the answer with other sources as well. That's just my understanding it could be wrong with extreme extent 

Regards,
Rahil

**Comment by kujason** [comment]
Several LiDAR-only methods include scale and translation augmentation, which may be helpful in improving performance. However, this is more difficult for fusion based approaches since scaling/translating the LiDAR points does not directly translate to resizing/shifting the image due to perspective projection.
