### ISSUE TITLE
GPU memory usage when training

### ISSUE THREAD

**Issue by sshaoshuai** [kujason/avod#37]
Hi, 
How much GPU memory do we need to train with your codes?
When training with your codes, the number of anchors among different images are different due to the distribution of lidar points, so will the GPU memory change in different batch?
Actually when I do the training, I found the GPU memory cost is always about 4GB, where I am curious.
Thanks very much.

**Comment by lihua213** [comment]
My GPU is 8G, however got InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

**Comment by melfm** [comment]
@sshaoshuai We usually train and evaluate the network on a single Titan Xp with 12 GB memory. The GPU memory allocation is handled by tensorflow, where using the flag `allow_gpu_mem_growth` indicates that memory will be allocated on demand, in power of 2 chunks, so if initially `4GB` has been allocated, if the next sample requires additional memory due to having large number of anchors, it then allocated `8GB` but this doesn't mean the model actually requires the entire chunk of memory. 

You can analyse the memory consumption on tensorboard, however this will show the actual allocated memory and not the actual memory the model is using.

Hope this helps.

**Comment by lihua213** [comment]
In my case, one 8G GPU is enough. the problem is caused by my tensorflow version. I solved my problem: update tensorflow 1.3 to tensorflow 1.6.

**Comment by xueyingliu** [comment]
@lihua213 I use one 4G GPU(nvidia 1050), and got the same error with you,
 `InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]
`
Follow your idea, I update my tensorflow 1.4 to 1.8 but still get the same error, do you have any idea? Due to my 4G GPU memory?

**Comment by ch-lai** [comment]
@xueyingliu  You can decrease the kernel number of VGG16 in config. With this change, it uses less memory during training. However, you probably will get lower performance.

**Comment by xueyingliu** [comment]
@ch-lai thanks, i'll try it.

**Comment by kujason** [comment]
Hi @xueyingliu, can you please confirm that you have the GPU version of tensorflow installed?
```
pip uninstall tensorflow
pip install tensorflow-gpu
```
The error message seems like you are using the CPU version

**Comment by Gebixiaochen** [comment]
@xueyingliu  Have you solved the problem? I set my GPU device = '0' but still have this problem.

**Comment by xueyingliu** [comment]
@Gebixiaochen Yes, my error disappeared after setting GPU device = '0', sorry for having no idea about your case.

**Comment by Gebixiaochen** [comment]
@xueyingliu Never mind! Thanks for your reply.So a 4G GPU is enough to run the training process?

**Comment by xueyingliu** [comment]
@Gebixiaochen 4G is not enough, I turn to a 8G GPU finally.

**Comment by Gebixiaochen** [comment]
@xueyingliu Thank you very much xueying! I still have some troubles in figuring out some details in the code. May I ask you some questions through email? Here is my email:chen20122550@gmail.com. Very appreciated for you help anyway.
