### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by karaspd** [kujason/avod#49]
I was wondering if anyone tried avod with other dataset. Also, if anyone can give instruction to setup avod with new dataset it would be great. Thank you.

**Comment by snarb** [comment]
Also it is interesring how good it can works without lidar data and in what tool we can draw 3d bounding boxes

**Comment by karaspd** [comment]
@melfm , @kujason I am looking into code to figure out how can I use completely new dataset without considering height map. As I underestand, the code is written specifically for kitti dataset in mind. If you can help me with how and where should I start would be greatly appreciated. 

From my study I need to modify following files and places:
dataset_builder
adding new_dataset, new_utils
protos for new_dataset
config files

**Comment by walzimmer** [comment]
I am also using AVOD on another dataset. I have changed the paths in the following files:

avod/configs/avod_cars_example.config -> dataset_dir
scripts/offline_eval/save_kitti_predictions.py -> predictions_root_dir
avod/datasets/kitti/kitti_dataset.py ->  self.dataset_dir
avod/builders/config_builder_util.py -> output_root_dir
demos/show_predictions_2d.py -> predictions_dir and output_dir_base

Furthermore I have removed the code for transforming an BGR image to an RGB image in kitti_dataset.py since I am using grayscale images. Currently I am creating a transformation matrix from Velodyne to camera space (similar to Tr_velo_to_cam in training/calib/000000.txt) and a projection matrix from camera to IMU space (similar to P2 in training/calib/000000.txt). The next step is to create ground planes (similar to planes/000000.txt) based on IMU data we have collected.

@melfm , @kujason I have read that AVOD does not work well with hilly scenes:
"Although this works fairly well on the KITTI dataset, this fails in the case where the ground-plane estimation is inaccurate due to hills in the environment and other variations where the ground-plane is highly variable." Should I use e.g. F-PointNet instead or is there another solution?

**Comment by ChengYiBin** [comment]
would u please tell me how to change the location of the KITTI dataset? in which file should i modified:
file avod/configs/avod_cars_example.config in line 135 --> # dataset_dir: '~/Kitti/object'
or, 
file avod/protos/kitti_dataset.proto in line 10 --> optional string dataset_dir = 2 [default = "~/Kitti/object"];
thanks

**Comment by Tsachi321** [comment]
@ChengYiBin 
I think that the only place is in /avod/protos/kitti_dataset.proto
line 11
optional string dataset_dir = 2 [default = "PATH/TO/DATASET"];
