### ISSUE TITLE
num_clusters: number of k-means clusters to separate for each class

### ISSUE THREAD

**Issue by villanuevab** [kujason/avod#63]
I missed the discussion of this value in the paper. Could you please explain where these clusters fit into the larger architecture? And why cars have num_clusters=2 while people (pedestrians, cyclists) have num_clusters=1? 

Thank you!

**Comment by melfm** [comment]
The k-means clustering is used to find initial appropriately sized anchors. The reason for using clusters is because, it is difficult to hand pick the best prior box dimensions. Since cars in terms of size, are more variable than people, you could use more clusters, however as the the number of clusters is increased, more anchors are generated and hence it requires more computation.

**Comment by kujason** [comment]
Yes that's correct, the first `num_clusters` lines are the cluster means (length, width, height), and the next `num_clusters` lines are the standard deviations.

**Comment by kargarisaac** [comment]
Would you please explain how can we use the avod model for multiclass problem? car/truck/pedestrian/bicycle/... in one trained model?
What do we need to change? number of clusters? number of generated anchor boxes on every grid point? 
I want to annotate a dataset and want to train a single model for all classes of car/truck/pedestrian/bicycle/...

**Comment by kujason** [comment]
The pedestrian and cyclists classes are trained together in one model. You can follow the same steps to extend the model to additional classes if needed.
