### ISSUE TITLE
Inference our data

### ISSUE THREAD

**Issue by xiaohedu** [kujason/avod#73]
Can someone explain this phenomenon?
we inference our data，the near bbox  is low , however , the bbox is high in the distance.
![0000001400](https://user-images.githubusercontent.com/8100660/41969513-38eb2f0e-7a3a-11e8-865f-68817cc84e98.png)

**Comment by kujason** [comment]
You will need to modify some of the input data to correspond with your car's setup (ground plane, camera projection matrix, etc.). The camera seems to be mounted lower than the KITTI camera, so the ground plane will be different, and the anchors and BEV may not be getting generated properly. Try modifying the `generate_anchors.py` and `kitti_bev_vis.py` to check your inputs.

**Comment by xiaohedu** [comment]
@kujason @melfm 
thank your for your reply.
1. our situation is that train data are from  simulation engine(camera height is 1.5m), then inference real-world data(camera height is 1.63 m), and we also re-calibrate our sensors. when we inference real-world  data ,how we should set  the constant ground planes value ( 1.5 or 1.63 )? 
2. when we detect people , the results are very bad. we need to some advice to adjust  which parameters for people detection? look forward for your answers , thank you!

**Comment by walzimmer** [comment]
@kujason @melfm @xiaohedu 
I have similar problems. The proposals are generated too high. That is why the detections are also too high:

![master_124_in-9900_000016_detections_too_high](https://user-images.githubusercontent.com/22540236/44018767-1aab09f2-9edd-11e8-8982-338203c5a4e3.png)

I am using grayscale images and duplicated the first channel three times to correspond to the algortihm.
Training was done on the KITTI dataset and now I am doing inference on our own data.

Furthermore our camera was mounted at 1.293m height (KITTI has a height of ~1.65).
Setting the height to -1.293 instead of +1.293 the anchors will be generated on the ground plane:

![master_130_in-9900_000012_anchors_correct_m1 293](https://user-images.githubusercontent.com/22540236/44023106-df54cbc4-9ee9-11e8-89da-1db4c0c3bb71.png)

But using a height of -1.293 I am not able to generate mini batches, because there are no points in the range from -0.2 to 2.3. The method create_slice_filter in kitti_utils will filter out all points in the pointcloud.

What is currently working is to use:
 - a height of +1.293 for generating mini batches
 - a height of -1.293 to generate the anchor grid
 - and a height of 0 to generate proposals 

The result is that proposals lie on the ground plane (having a correct height) but are still wrong in the lateral and longitudinal position:

![master_129_in-9900_000012_anchors_wrong_lat_position](https://user-images.githubusercontent.com/22540236/44023997-56701630-9eec-11e8-862a-7bf8a1ab5425.png)



Does anyone know why the proposals are generated at the wrong position?
The projection matrix should be fine, since the ground truth labels are projected correct.
My guess is that we use a different camera with a focal length of 1613px (6.05mm) 
Training was performed on the KITTI dataset using a camera with focal length of 960px (3.601mm)

**Comment by xiaohedu** [comment]
sorry , see that so late!
     my  calibration matrix  are uncorrected ,  and your ground truth label have a  bit doubt( in red ). so I think you can try to calibrate them again. thank you !

**Comment by yinhai86924** [comment]
> @kujason @melfm
> thank your for your reply.
> 
> 1. our situation is that train data are from  simulation engine(camera height is 1.5m), then inference real-world data(camera height is 1.63 m), and we also re-calibrate our sensors. when we inference real-world  data ,how we should set  the constant ground planes value ( 1.5 or 1.63 )?
> 2. when we detect people , the results are very bad. we need to some advice to adjust  which parameters for people detection? look forward for your answers , thank you!

**Comment by yinhai86924** [comment]
> sorry , see that so late!
> my calibration matrix are uncorrected , and your ground truth label have a bit doubt( in red ). so I think you can try to calibrate them again. thank you !

how to generate the calibration matrix for each frame? I get the calib_velo_to_cam from kitti raw data: as follows:
calib_time: 15-Mar-2012 11:45:23
R: 7.967514e-03 -9.999679e-01 -8.462264e-04 -2.771053e-03 8.241710e-04 -9.999958e-01 9.999644e-01 7.969825e-03 -2.764397e-03
T: -1.377769e-02 -5.542117e-02 -2.918589e-01
delta_f: 0.000000e+00 0.000000e+00
delta_c: 0.000000e+00 0.000000e+00
how to get calib as training folder shows?
for example in calib folder/000000.txt include:
P0: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 0.000000000000e+00 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P1: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.797842000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P2: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 4.575831000000e+01 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 -3.454157000000e-01 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 4.981016000000e-03
P3: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.341081000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 2.330660000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 3.201153000000e-03
R0_rect: 9.999128000000e-01 1.009263000000e-02 -8.511932000000e-03 -1.012729000000e-02 9.999406000000e-01 -4.037671000000e-03 8.470675000000e-03 4.123522000000e-03 9.999556000000e-01
Tr_velo_to_cam: 6.927964000000e-03 -9.999722000000e-01 -2.757829000000e-03 -2.457729000000e-02 -1.162982000000e-03 2.749836000000e-03 -9.999955000000e-01 -6.127237000000e-02 9.999753000000e-01 6.931141000000e-03 -1.143899000000e-03 -3.321029000000e-01
Tr_imu_to_velo: 9.999976000000e-01 7.553071000000e-04 -2.035826000000e-03 -8.086759000000e-01 -7.854027000000e-04 9.998898000000e-01 -1.482298000000e-02 3.195559000000e-01 2.024406000000e-03 1.482454000000e-02 9.998881000000e-01 -7.997231000000e-01

**Comment by yinhai86924** [comment]
> sorry , see that so late!
> my  calibration matrix  are uncorrected ,  and your ground truth label have a  bit doubt( in red ). so I think you can try to calibrate them again. thank you !
您好！您能分享一下您的3D目标检测数据集吗？ 如果自己制作，需要传感器校准得到那些数据？ 谢谢了！

**Comment by kujason** [comment]
Try visualizing your data in 3D to get a better idea of what's wrong. #66
